### PR TITLE
add coveralls to ci

### PR DESCRIPTION
**Pull request by StephenRadachy**

### CODE REVIEW

**Comment by liclac** [comment]
The build seems to be failing…

**Comment by StephenRadachy** [comment]
I'll get it figured out when I have some free time this coming week. In the meantime, @liclac can you add the coveralls API token as an environment variable to circleci per https://github.com/mattn/goveralls#circleci

**Comment by liclac** [comment]
`$COVERALLS_TOKEN` added to the environment!

**Comment by borjacampina** [comment]
@StephenRadachy check my merged PR/last commit, I have added some goveralls steps but there is no changes at https://coveralls.io/github/loadimpact/k6 page

**Comment by liclac** [comment]
Ah, that would be because it refers to $COVERALLS_REPO_TOKEN, when we're actually setting $COVERALLS_TOKEN, I'll try changing that.

**Comment by robingustafsson** [comment]
Same as for https://github.com/loadimpact/k6/issues/345: closing this as we have codecov implemented and it feels like it's working nicely for us. Thanks for PR @StephenRadachy.

**Pull request closed without merging**
