### PR TITLE
Fix: windows installer

### PR DESCRIPTION
**Pull request by mostafa**
Hi,

I have added the new k6 logo plus its icon and banners to the windows installer. Upon getting the code signing certificate, I'll fix the package signing across all distributions, especially #1034 and #1247.

Also, the current ".ico" file is not used to make a k6 executable, ~so I created a ".syso" file using [rsrc](https://github.com/akavel/rsrc) tool. The `go build` process picks it up and includes it in the final executable file.~ so I used [goversioninfo](https://github.com/josephspurrier/goversioninfo) to generate a resource file to accompany the `go build` process.

I don't expect a new release just for the sake of this small change, so this PR can wait for the next release, or you decide.

### CODE REVIEW

**Comment by na--** [comment]
https://github.com/josephspurrier/goversioninfo this also looks like a good tool to furnish other useful data besides the icon file in the `.syso` file. And when you have a `go:generate` directive, it offers us a reproducible way to generate the binary `.syso` file, instead of simply checking in a binary in git.

**Comment by imiric** [comment]
Hey guys, what's the status of this? @mostafa Are you still willing to work on it?

It will need to be updated to GitHub Actions and implementing that templating proposal by @na--.

**Comment by mostafa** [comment]
@imiric It would be awesome if you can take over. I can test it afterward.

**Comment by imiric** [comment]
Closing this in favor of #1727.

**Pull request closed without merging**
