### PR TITLE
replace demo svg with a gif

### PR DESCRIPTION
**Pull request by simskij**
resolves the issue mentioned in https://github.com/loadimpact/k6/issues/233#issuecomment-543184882 with @imiric's laptop hovering a decimeter above his desktop

### CODE REVIEW

**Comment by MStoykov** [comment]
I guess svgs are heavier? 
But either way 
1. your gif resolution is WAY too big it will be best if it looks okay just looking at it in the readme instead of needing it to open in order for the text to not be awful ... also even on it's own it is way too big :D 
2. the k6 logo isn't aligned for you for some reason ...

**Comment by simskij** [comment]
> I guess svgs are heavier?
> But either way
> 
> 1. your gif resolution is WAY too big it will be best if it looks okay just looking at it in the readme instead of needing it to open in order for the text to not be awful ... also even on it's own it is way too big :D
> 2. the k6 logo isn't aligned for you for some reason ...

I replaced the gif with a more optimized one with lower res and the k6 logo aligned. Could you please check again? 😇

The biggest difference, which I guess is why it stressed his laptop, is that SVG's are rendered using paths, and in this case animated paths, while gifs are frame by frame static pixel content.

**Comment by imiric** [comment]
Hhmm how come the GIF with the higher resolution was 119k, and the new smaller one is 481k?

Originally I thought GIFs would be much bigger in file size, but this is not too bad if we can get it under 100k.

**Comment by simskij** [comment]
> Hhmm how come the GIF with the higher resolution was 119k, and the new smaller one is 481k?
> 
> Originally I thought GIFs would be much bigger in file size, but this is not too bad if we can get it under 100k.


That sounds like a very arbitrary number, but I'll go with it! 😅 The reason why the smaller one is larger is due to length, as I re-recorded it without asciinema.

Had to cut some frames and make the res even lower, but there's now a version which is roughly 90kb.  👍

**Comment by imiric** [comment]
Yeah, a bit arbitrary, but I assumed that a lower res version of the 119k one would be smaller in size still.

The latest 130kb version is a bit blurry, but still legible. I'm OK with going with that.

**Comment by simskij** [comment]
> Yeah, a bit arbitrary, but I assumed that a lower res version of the 119k one would be smaller in size still.
> 
> The latest 130kb version is a bit blurry, but still legible. I'm OK with going with that.

Yeah, unfortunately it will never be as crisp as the vector one, but at least it wont make your laptop fly to Sweden when you open the repo!

**Comment by simskij** [comment]
> LGTM, just remember to squash before merging so we don't end up with multiple revisions in the repo :D, and wait for more approvals. :)

Squashed!

**Pull request merged**
