### PR TITLE
Expose effective URL in HTTP response

### LINKED ISSUE #133: Need access to effective URL after redirect

### PR DESCRIPTION
**Pull request by ragnarlonn**
Closes #133

### CODE REVIEW

**Comment by uppfinnarn** [comment]
Just call it `url` imo

**Comment by ragnarlonn** [comment]
I thought that might be ambiguous. Tagging on the word "effective" indicates clearly that it is something different from the URL supplied to http.request().  But if everyone thinks it won't cause confusion I'm all for it.

**Comment by uppfinnarn** [comment]
I don't think there's much of a point in disambiguating here, it doesn't make much sense to provide any other URL in a response than the URL the response was fetched from.

**Comment by ragnarlonn** [comment]
I just don't like the general concept of using the same keyword within the same context to mean two different things, but OTOH people aren't even going to know there *is* a `url` parameter being returned unless they read the docs I guess, and it is simple to explain there.

**Comment by ragnarlonn** [comment]
@uppfinnarn mergymerge!

**Comment by uppfinnarn** [comment]
@ragnarlonn Can't see why that check is failing on my phone, but I can if you fix that if you don't wanna wait for me to get back on my laptop!

**Comment by ragnarlonn** [comment]
@uppfinnarn it's our old friend "[]" should have 1 item(s), but has 0  :)

**Pull request merged**
