### PR TITLE
chore: format import statement

### PR DESCRIPTION
**Pull request by thinkerou**
first part: the standard package
second part: third package
third part: k6 package

### CODE REVIEW

**Comment by thinkerou** [comment]
have the follow error:
```
go version go1.14.3 linux/amd64
cmd/pause.go:29:2: cannot find package "github.com/loadimpack/k6/api/v1" in any of:
	/home/circleci/.go_workspace/src/github.com/loadimpact/k6/vendor/github.com/loadimpack/k6/api/v1 (vendor tree)
	/usr/local/go/src/github.com/loadimpack/k6/api/v1 (from $GOROOT)
	/home/circleci/.go_workspace/src/github.com/loadimpack/k6/api/v1 (from $GOPATH)
```

**Comment by thinkerou** [comment]
I only change order: https://github.com/loadimpact/k6/pull/1464/files#diff-f2ba53414ba64f2e71d42ad483572e4cR29

but have the follow error:
```
go version go1.14.3 linux/amd64
cmd/pause.go:29:2: cannot find package "github.com/loadimpack/k6/api/v1" in any of:
	/home/circleci/.go_workspace/src/github.com/loadimpact/k6/vendor/github.com/loadimpack/k6/api/v1 (vendor tree)
	/usr/local/go/src/github.com/loadimpack/k6/api/v1 (from $GOROOT)
	/home/circleci/.go_workspace/src/github.com/loadimpack/k6/api/v1 (from $GOPATH)
```

**Comment by thinkerou** [comment]
> You have a typo, `loadimpack` should be `loadimpact` ...

@na-- oh...fixed, thanks!

**Comment by thinkerou** [comment]
> The `rice-box.go` files are `go:generate`d files, so you shouldn't change them manually. Please revert those, the other changes seem fine.

@na-- thanks! suggest to add `DO NOT EDIT` sign like `elements_gen.go` and file name add `_gen.go` postfix.

**Comment by na--** [comment]
Feel free to use this PR to rename them (and adjust the `go:generate` commands) to have `_gen.go` in the name :wink:

**Comment by thinkerou** [comment]
> Feel free to use this PR to rename them (and adjust the `go:generate` commands) to have `_gen.go` in the name 😉

OK, I will reopen one pr to solve it -- `rice_box_gen.go`

**Pull request merged**
