### PR TITLE
Multistage k6 Dockerfile

### LINKED ISSUE #371: Separate docker containers into "build" and "run"
The provided Docker container's (`loadimpact/k6`) base is `golang:1.9-alpine`. However golang is just used for building the binary, and not needed at runtime.

The final container size could be reduced even more by building the binary on `golang:1.9-alpine`, and then copying the binary onto a plain `alpine` container.

### PR DESCRIPTION
**Pull request by borjacampina**
close #371 

This is my proposal for a new multistage Dockerfile for the k6 image.
It looks like we only need the git dependency, I have removed make and build-base ones.
I have embedded the js/compiler resources with rice.

Comparison size:
```
loadimpact/k6       0.2.2               1f56545378ee        6 minutes ago       50.6MB
loadimpact/k6       latest              957fcf856ced        3 weeks ago         301MB
```

### CODE REVIEW

**Comment by borjacampina** [comment]
I have included build tools again to generate a static build (needed for the scratch base image). I have used `-ldflags '-s -w'` too. The k6 binary and the new docker image are much smaller:

```
loadimpact/k6       0.2.2               75dc950c164a        Less than a second ago   38.4MB
```

**Comment by borjacampina** [comment]
The first test call is failing (only this line) because k6 scratch image is a "single-binary" image (https://hub.docker.com/_/scratch/), we can't execute /bin/sh. Switching from a scratch baseimage to a alpine one is not a solution, we haven't a go development environment there neither.

I have modified the check goal from the actual Makefile to **ignore vendor/ folder**.
I have updated circleci config file to use a golang:1.9-alpine image to run gometalinter and go tests but it looks like I can't use `-v $(PWD):/go/src/github.com/loadimpact/k6` in circleci.

WIP

**Comment by borjacampina** [comment]
More changes, I have reordered some steps (launching tests before building the docker image).

It looks like the tests are not working, I have to handle the vendor folder issue:

```bash
gometalinter --deadline 10m --config gometalinter.json $(go list ./... | grep -v vendor)
go test -timeout 30s $(go list ./... | grep -v vendor)
```
WIP

**Comment by borjacampina** [comment]
@liclac, It looks like there is some issue with the godep/vendor folder change.

Running `gometalinter --deadline 10m --config gometalinter.json --vendor ./...` shows:

```
api/server_test.go:52:16:warning: cannot use log.DebugLevel (constant 5 of type github.com/loadimpact/k6/vendor/github.com/sirupsen/logrus.Level) as github.com/sirupsen/logrus.Level value in assignment (gosimple)
```

Outdated sirupsen/logrus dependency?

**Comment by borjacampina** [comment]
Ok, I think linter and tests are working again

**Comment by borjacampina** [comment]
Tests fails randomly. I think this happens because some connection issues with the external service echo.websocket.org

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
/home/circleci/.go_workspace/src/github.com/loadimpact/k6/js/modules/k6/ws/ws_test.go:96 +0x43
FAIL	github.com/loadimpact/k6/js/modules/k6/ws	0.802s
```

**Comment by StephenRadachy** [comment]
I think there should be multiple base image versions available for people to consume.

1. Debian base (default)
2. Alpine base <version>-alpine
3. Scratch base <version>-scratch or <version>-binaryonly?

I ❤️ the idea of a scratch image, but having it as the only option available increases the barrier of entry for some and could be a deterrent to others. We want k6 to be as accessible and easy to use as possible :).

One potential solution would be to have the circleci run step build a static binary using the existing golang image. During the deploy stage, we can then use that image to build/push/tag multiple multi-stage images by copying over the binary from it.

**Comment by borjacampina** [comment]
My initial idea was to create the smallest possible docker image of the k6 tool. To reduce the wait time and disk resources to use/test a specific version of k6.

Do you think it's common to use this image of k6 (alpine, debian.. based) as a base image? I have not even thought of it. You can always grab the k6 binary file in you preferred flavor of docker base image with:

```bash
VERSION=0.18.0
curl -sL https://github.com/loadimpact/k6/releases/download/v${VERSION}/k6-v${VERSION}-linux64.tar.gz | tar xz --strip-components 1
```

**Comment by liclac** [comment]
I do like the idea of multiple docker tags, but having the default image be as small as possible is ideal in my mind. I'm gonna merge this because it's a definite improvement, but I'd absolutely merge a PR adding alternate base images.

**Pull request merged**
