### PR TITLE
In-process ES6 compiler, dropping Node dependency!

### PR DESCRIPTION
**Pull request by uppfinnarn**
TESTING REQUESTED!

Replaces the subprocess calls to Babel with an in-process goja VM. Also replaces babel-polyfill with a submodule'd core-js copy.

I'd like to ask everyone who's able to do so to try running their scripts using this branch before merging it, because there may be subtle breakages in the process (notably, there was a [now-fixed goja issue](https://github.com/dop251/goja/issues/15) wherein incorrect code was produced, and I only found out because it choked on k6/metrics.js).

### CODE REVIEW

**Comment by uppfinnarn** [comment]
Note: the JS libraries are submodules now, which is to my knowledge the cleanest way to do it.

If you get panics on launch about missing files, run `git submodule update --init` and it'll work. AFAIK `go get` will pull down submodules properly as well, but I'm open to suggestions for alternative approaches.

**Comment by pnn** [comment]
don't forget to add instructions about submodules to the docs!

**Comment by uppfinnarn** [comment]
There!

**Comment by uppfinnarn** [comment]
Since I haven't heard any reports of broken scripts, I'm merging this as soon as that CI build finishes.

**Pull request merged**
