### PR TITLE
Enable logstash log format

### PR DESCRIPTION
**Pull request by ivoreis**
Sometimes is useful to pipe logs to external sources. 
[Logstash](https://www.elastic.co/products/logstash) is a very common data source pipeline.

This PR enables a logstash compatible log format:
```
{"@timestamp":"2017-12-19T18:46:16Z","@version":"1","level_name":"debug","message":"Engine terminated cleanly"}
```
instead of:
```
DEBU[0010] Engine terminated cleanly
```

Usage cmd:
```
k6 run samples/http_get.js --format logstash
```

### CODE REVIEW

**Comment by liclac** [comment]
Nice work!

Rather than using a specific `--logstash` flag though, could you make it a `--fmt` (or something of that nature) flag that takes an argument for the kind of formatting you want?

**Comment by liclac** [comment]
There's also the option of sending data directly to logstash: https://github.com/bshuster-repo/logrus-logstash-hook (`--log logstash=http://1.2.3.4:5678/`)

(Though I actually thought the idiomatic way to send stuff to logstash was to use JSON output and Beats?)

**Comment by liclac** [comment]
Yeah, I agree. Any reason not to use the built-in JSONFormatter in that case?

**Comment by ivoreis** [comment]
Do you have a custom JSON formatter already or you're talking about the default one? The case of being the default we need a custom one to generate a [specific format](https://www.elastic.co/guide/en/logstash/current/config-examples.html).

Question about the file logger.go, I don't think that's the adequate name. **name** and **location**  for it? Suggestions?

**Comment by liclac** [comment]
I'd put it in `lib`, honestly. If it grows to become more than one collector, I'd probably make a separate package.

And correct me if I'm wrong, but isn't the idiomatic way to do this not to have applications output logstash-y JSON, but to output regular JSON and tell logstash which field is the timestamp, etc.?

**Comment by ivoreis** [comment]
Ok.
I don't know what's the idiomatic way of doing that but I always try not to do any heavy lifting inside the app in terms of logging (logstash is good at that). In this case we're just adding some extra compatible keys and most importantly normalise the output msg field to appear as an aggregate / one line only.

**Comment by liclac** [comment]
Yeah. The JSONFormatter included with logrus seems to be able to do that? (I haven't actually tried piping it to logstash)

**Comment by ivoreis** [comment]
Yep you're right. The default logrus logger will output something very similar and handles multi line too. That's cool. 

I guess I'll update the logger format name to be json instead of logstash. Or we can have both, logstash that formats the json to a logstash-ish format and json that outputs the log on a json format

**Comment by ivoreis** [comment]
I'm closing this one for now and open a new json logger one

**Comment by liclac** [comment]
Ah, you could've just changed the title...

**Pull request closed without merging**
