### PR TITLE
Implement http.batch()

### PR DESCRIPTION
**Pull request by pnn**
[WORK IN PROGRESS]

this implements #72. api is as described in the original issue:

```js
let responses = http.batch([
  "http://test.com",
  {
    "method": "GET",
    "url": "http://test.com?cool=1"
    // optionally, body or params
  }
])
```

the only problem that currently exists with this implementation is that the array of responses is jumbled, making is pretty difficult to `check()` single requests. i wanted to gather some opinions on how to best solve this here before attempting to do so myself, as i'm not quite sure how to go about this

### CODE REVIEW

**Comment by micsjo** [comment]
Prefer to have responses in the same order as the requests. If not there would need to be some means of identifying them to match response <> request.

**Comment by ragnarlonn** [comment]
Agree with @micsjo - is it hard to get the response elements in a particular order?  IMO, it is pretty intuitive that if you send in http.batch([req1, req2, req3]) you would get back [resp1, resp2, resp3].

**Comment by pnn** [comment]
yeah, this is the problem i was talking about. the requests array doesn't have any indicators to keep them in a specific order, so my best guess would be to assign a temporary id to each of them and reorder the responses array based on those. @uppfinnarn do you have any other ways to solve this?

**Comment by uppfinnarn** [comment]
The way it was implemented, I took an otto.Value as the first argument, then looped through it, replacing each value with the corresponding response. That means objects and arrays both work the same, by the way.

**Comment by pnn** [comment]
@uppfinnarn accepting objects as parameters seems somehow useless to me, since the keys would be disregarded. why not only accept arrays (we can still handle it ambiguously behind the scenes)?

**Comment by uppfinnarn** [comment]
Mostly, it let you do either `http.batch([url1, url2])` -> `[res1, res2]` or `http.batch({a: url1, b: url2})` -> `{a: res1, b: res2}`.

You can do the assignment with a mutex from inside the request goroutines themselves, rather than appending.

**Comment by pnn** [comment]
ah, that makes sense

**Comment by pnn** [comment]
@uppfinnarn @ragnarlonn @micsjo this should be ordering things correctly now

**Comment by uppfinnarn** [comment]
There should be some unit tests for it. (Pull in the compiler change from develop and use `go test -v -run [regex]` for faster tests, or running them will take all day.)

**Comment by pnn** [comment]
test are added, and passing

**Pull request merged**
