### PR TITLE
We actually need to disable sourceMaps when we compile them as well

### PR DESCRIPTION
**Pull request by MStoykov**

### CODE REVIEW

**Review by na-- — DISMISSED** [review]
LGTM, why not update goja as well?

**Comment by MStoykov** [comment]
I wanted to also enable some tc39 tests with a new version and do it in another PR. But I already started running the tests so I can add to this one if you want to :)

**Comment by na--** [comment]
However you prefer to do it, but :+1: for a goja update today from me

**Comment by na--** [comment]
btw I have no idea how source maps work precisely, but would this change be too difficult to test?

**Comment by MStoykov** [comment]
It literally cares about a comment at the end of a source file
```javascript
//# sourceMappingURL=ajv.min.js.map
```

**Review by na-- — APPROVED** [review]

**Review by imiric — APPROVED** [review]
LGTM, but this is breaking change, no? Sourcemaps were supported before?

**Comment by MStoykov** [comment]
if they at any point worked in any capacity it wasn't intentional ;) 
Given the issues listed (and now fixed) in https://github.com/dop251/goja/issues/235  I would expect  that they never did for us

**Pull request merged**
