### PR TITLE
initiate go module

### PR DESCRIPTION
**Pull request by wingyplus**
Updates #1070

### CODE REVIEW

**Comment by wingyplus** [comment]
Should we need to keep for Go1.12 ci pipeline. Or use dep ensure to fetch dependencies before running test?

**Comment by cuonglm** [comment]
> Should we need to keep it for Go1.12 ci pipeline. Or use dep ensure to fetch dependencies before running test?

I think we can completely remove dep and vendor.

For go1.12 pipeline, we can run:

```
go mod edit -go=1.12
```

before running the test.

**Comment by na--** [comment]
> We are switching to go module, then I think we can drop vendor directory, and setup proper CI/CD flow to adopt go module.

Why do you want to drop `/vendor`? I'd be very reluctant to do so, even with the new official Golang module mirror. I like the safety, predictability, and visibility of having all of the k6 dependencies in our own repo. The visibility is especially useful in helping us avoid very fat or needless dependencies, so that we don't unnecessarily explode the footprint of code we depend on... 

> Should we need to keep it for Go1.12 ci pipeline. Or use dep ensure to fetch dependencies before running test?

Go modules should work just fine in Go 1.12, we shouldn't need `dep` there :confused: 

Also, please don't actually update the dependencies when switching to go modules - it makes this PR very difficult to review. The dependency update should be in a separate pull request, or at the very least, in a separate commit...

**Comment by cuonglm** [comment]
> Go modules should work just fine in Go 1.12, we shouldn't need dep there 

The `go.mod` only allows 1 go version.

If we do want to keep vendor directory, then go1.12 pipeline can be run with `-mod=vendor` 🤔

**Comment by na--** [comment]
If we have vendor (and I still see no reason to remove it), we should probably use it for all builds - 1.12, 1.13 and so on. For one, given that CI systems will build the project in fresh containers, using the local vendored files will be faster than retrieving them over the network every time...

I had to read through a bunch of Go issues, and to be honest, I'm far from satisfied with how tacked on and poorly supported vendoring is in the go modules world :disappointed: I loosely followed the Go modules saga, but I never realized that backwards incompatibility, I just assumed things would work as they used to, backwards compatibility and all... :disappointed: 
 
In any case, it seems like most issues will be fixed in Go 1.14, but until then, we'd have to rely on things like `-mod=vendor` if we want both go modules and vendoring... Or, more likely, on `GOFLAGS=-mod=vendor`. Some links if anyone else wants to follow the related discussions:
- https://github.com/golang/go/issues/27227: long read, but worth it
- https://github.com/golang/go/issues/27348: would have been nice to have as a CI task, like we [currently do with `dep`](https://github.com/loadimpact/k6/blob/a2077dd22a86662ef3cd699bc57b0048136e51ba/.circleci/config.yml#L12-L20), but seems like we'd have to wait
- https://github.com/golang/go/issues/29058: yeah, you don't say... :smile: 
- https://github.com/golang/go/issues/30240: previous proposal for fixing the current deficiencies, with [this comment](https://github.com/golang/go/issues/30240#issuecomment-516735768) in particular making a ton of sense
- https://github.com/golang/go/issues/33848: the current proposal, probably what we should follow closely

**Comment by cuonglm** [comment]
@na-- I think we should only use go module for vendor management only, so the process will be:

 - go mod tidy
 - go mod vendor

Then in CI/CD, we will explicitly set `GO111MODULE=off`.

**Comment by na--** [comment]
:+1: seems reasonable, it may be an easier workaround until vendoring is properly supported in Go 1.14, but as I've seen today, I'm far from an expert in Go modules...

**Comment by wingyplus** [comment]
@cuonglm  @na--  I think we can use go module mode on go1.12 by using enabling GO111MODULE. This can be the same as setting on go1.13.

**Comment by cuonglm** [comment]
> @cuonglm @na-- I think we can use go module mode on go1.12 by using enabling GO111MODULE. This can be the same as setting on go1.13.

Yes, you can.

But the issue is that go.mo specify go1.13 version, so without  editing go.mod, building using go1.12 will fail. That's why I said it's better to use go module for vendoring only, then in CI/CD, just turn off GO111MODULE and build using vendor.

**Comment by wingyplus** [comment]
I found test failing on go1.13 in the current build of this [pr](https://circleci.com/gh/loadimpact/k6/6606?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link): 

```
--- FAIL: TestSentReceivedMetrics (36.73s)
    --- FAIL: TestSentReceivedMetrics/group (0.00s)
        --- FAIL: TestSentReceivedMetrics/group/SentReceivedMetrics_script[3]_case[4](25,2) (3.11s)
            engine_test.go:624: noReuseReceived=28325.000000 is greater than reuseReceived=28329.000000
```

Not sure is it flaky test?

**Comment by wingyplus** [comment]
@cuonglm I think we edit go.mod to `go 1.12` at minimum version to support both version in CI. And we'll bump to `go 1.13` when go 1.14 release. What do you think?

**Comment by cuonglm** [comment]
> @cuonglm I think we edit go.mod to `go 1.12` at minimum version to support both version in CI. And we'll bump to `go 1.13` when go 1.14 release. What do you think?

Ah, sound good :+1: 

And also, the test false is flaky one, see #https://github.com/loadimpact/k6/pull/1149

**Comment by wingyplus** [comment]
@cuonglm Thanks for your pointing out an issue. I'll wait until it fix and rebase to test again if #1149 got merged to master. :)

**Comment by wingyplus** [comment]
`test-prev-golang` task work as expect :tada:

**Comment by thinkerou** [comment]
hi any updates? merged before #1007 ? thanks!

**Comment by na--** [comment]
@thinkerou, moving to use go modules will definitely have to wait until after #1007 is merged... Maybe we'll do it in conjunction with #959. 

Also, we want to keep vendoring our dependencies, so we had to wait for Go 1.14 (see linked golang issues in https://github.com/loadimpact/k6/pull/1150#issuecomment-530256215), and this is something that this PR doesn't address, so when the time comes, we'll probably close this and make a new PR.

**Comment by thinkerou** [comment]
@na-- got it, thank your reply!

**Comment by imiric** [comment]
@wingyplus Thanks for your work on this, but we did it from scratch in #1584, which is now merged, so closing this.

**Pull request closed without merging**
