### PR TITLE
Add travisci integration

### PR DESCRIPTION
**Pull request by borjacampina**
Add travis-ci integration. You have to include DOCKER_AUTH and DOCKER_EMAIL env variables to the https://travis-ci.org/loadimpact/k6/settings section.

Three stages:
* linter
* tests (that run in parallel) for multiple go versions (1.9, 1.8). For 1.9, it generates code coverage too
* dockerimage: build image, test docker container and push docker image if needed

### CODE REVIEW

**Comment by borjacampina** [comment]
silly circle ci, this PR doesn't affect the tests

**Comment by liclac** [comment]
@robingustafsson Do you have the values for these?

**Comment by robingustafsson** [comment]
@liclac @borjacampina Yes I do, I've added them to Travis as env vars now. What is the rationale for adding/switching to Travis? Didn't we solve the coveralls issue by using codecov instead (https://github.com/loadimpact/k6/pull/382)?

**Comment by borjacampina** [comment]
Travis have a feature called build matrix that gives the opportunity to run tests on multiple golang versions and environment vars at once.

https://docs.travis-ci.com/user/customizing-the-build/#Build-Matrix
https://docs.travis-ci.com/user/build-stages/matrix-expansion/

In the proposed config file we are using two different versions of go:

```yaml
go:
  - 1.9
  - 1.8
```

**Comment by liclac** [comment]
It also feels better supported by the community in general.

**Comment by MStoykov** [comment]
I am closing this as there hasn't been any movement on it. Additionally circleci is currently providing us with everything we need and moving to travis will need to add something in order for us to make the change. 

Thanks @borjacampina , I am actually somewhat interested in building in both travisCI and circleCI, but maybe at a later time :)

**Pull request closed without merging**
