### PR TITLE
Add `install.sh` script

### PR DESCRIPTION
**Pull request by ppcano**
Now, that #393 has been merged, we could add the `install.sh` script to provide the possibility to install `k6` as:

```
curl -sfL https://raw.githubusercontent.com/loadimpact/k6/master/install.sh | sh
```

This was discussed at #392. I don't think `install.sh` should be the recommended installation instruction because it won't work for most of the `windows` users, but it could be useful for Mac users.

### CODE REVIEW

**Comment by liclac** [comment]
Instead of this, maybe we could offer some easy way to `wget` the latest k6 binary?

It feels silly to have an entire script like this (…especially with the security implications of `curl | sh`…), when essentially all it does is `wget https://example.com/k6 -O /usr/local/bin/k6`.

**Comment by ppcano** [comment]
@liclac 

I just copy the idea from  [godownloader](https://github.com/goreleaser/godownloader) and  [gorelease](https://github.com/goreleaser/goreleaser). This is common for other CLI tools written in `go`.

> It feels silly to have an entire script like

This `install.sh` script is usually generated by [godownloader](https://github.com/goreleaser/godownloader), I just modified an existing `install.sh` to fit the `k6` release flow.

> especially with the security implications

This is why the `checksum` validation has been added. Users who trust your instructions will use the command, others will use other alternative instructions.

I am in favor of any other solutions, but this will have to be implemented.
```
wget https://example.com/k6 -O /usr/local/bin/k6
```

I don't see a big problem with having a script like `install.sh`, we have to experiment what the better installation instructions may be. If something does not work or there is a better solution, we can always remove the script and change the instructions. 

As I said before, I don't think the `install.sh` command should be the recommended instructions because it will only fit for some Mac users.




I have been also discussing the packaging with @robingustafsson. [equinox.io](https://equinox.io/docs#packaging) looks to solve this problem.

**Comment by liclac** [comment]
The checksums don't matter if the entire file gets MITM'd. What generated it won't matter when it's long as heck and a pain to audit yourself before running it. `curl|sh` is a security disaster, because you're running arbitrary code off the internet with no reasonable way to audit what it does, or to tell if it's changed between you reading and running it (if you read it at all).

The mac already has Homebrew, I have no idea what state our Linux packages are in.

**Comment by ppcano** [comment]
Closing

**Comment by ppcano** [comment]
Just for reference, https://github.com/tj/bins uses the similar instructions than @liclac is suggesting.

**Pull request closed without merging**
