### PR TITLE
Feature/ecommerce script sample

### PR DESCRIPTION
**Pull request by ragnarlonn**
This script depends on being able to access the redirected URL after a redirect happens (PR#134) and currently uses the `res.effective_url` name (i.e. this script needs to be updated in case we decide to call the redirected URL `res.url` instead).

### CODE REVIEW

**Comment by ragnarlonn** [comment]
Hmm , the PR#134 change snuck into this PR also...ah well, I'm too tired to fix that now.

**Comment by adr0sen** [comment]
@ragnarlonn - just trying to run test script in this PR, it complains about missing `users.json`? I'm assuming we will provide a default such file?

**Comment by uppfinnarn** [comment]
@ragnarlonn Needs updating for #134

**Comment by ragnarlonn** [comment]
@adr0sen I put some username/password data inline instead, so we don't need an extra file just to run the script.

**Comment by ragnarlonn** [comment]
@uppfinnarn any problem with merging this now?

**Comment by ragnarlonn** [comment]
@uppfinnarn ping?

**Comment by uppfinnarn** [comment]
Since this script will be a reference point for what idiomatic k6 scripts look like, we need to go through them and make sure that it's a shining example of that - right now, I don't feel like it is.

A couple of quick comments off the top of my head:

- Everything is in one file, some parts may be better broken out into separate ones.
- The huge list of static assets looks clunky, highlighting the need for an idiomatic approach to getting external resources out of an HTML file.
- Use of global variables in a way that looks odd.
- There's a lot of cache code, highlighting the issue in #142.
- `|| console.log(...)`? Wouldn't `|| throw new Error(...)` make more sense?
- No groups or anything else, the organization is all over the place.

**Comment by ragnarlonn** [comment]
@uppfinnarn I understand what you mean, but we *seriously* need to start pushing some example code and better documentation out there. Now!  Our early users are extremely important and by not giving them any help we are going to make them churn, which is very very bad at such an early stage of a project. I would agree with you that for a more mature project it is very important to maintain a high quality throughout the repo, but right now people need help!  That's what I heard Yolanda say in her feedback, at least, and what I can see myself looking at the project.

We need to be able to push out less-than-perfect documentation and code examples that we can ITERATE on and improve over time. Please tell me how we can accomplish this in a way that is acceptable to you. We could use a "contrib" prefix or whatever, to signify that this is less perfect than we would like it to be, but it is important people find it also, so we shouldn't hide it in some impossibly remote subdirectory somewhere.

**Comment by uppfinnarn** [comment]
I completely agree that getting documentation out there ASAP is important, but the one thing that does more damage than no docs is ***wrong*** docs. If one of our sample scripts is not only needlessly complicated but also written in a way that would be idiomatic Lua, not JS, with no groups or proper organization, imagine what would happen if that's the first thing they see.

I'm not saying it has to be perfect before we merge it, I'm saying it has to be readable and at least have some semblance of idiomatic code in it. We can add more features later, but the groundwork here is broken. I'd love to just sit down with you and work this out whenever it's possible, or you can just send me questions whenever.

**Comment by ragnarlonn** [comment]
"Wrong" for most people is when something doesn't work. With docs, that means it doesn't help the user accomplish what they want to do. An example that is not idiomatic, but which shows the user how something can be done, works for most users and is endlessly better than no example at all. Taking something as simple as code examples through the lengthy process we see in this thread is counterproductive to making k6 become a successful project. It was two weeks since this was first committed now, and it took 11 days until I got some *real* feedback on the commit!

We need more code examples yesterday, and I can produce many examples in short time - if I am allowed to. I think you have an idea that the people who will be looking at k6 will be just like you, but they are not. They are almost exclusively less proficient programmers, less bothered with idiomaticity, less likely to go "what crappy ES6 code this is!  This whole app is probably crappy, I'll skip it". People who just need help getting started will not judge us on HOW they get started. So the best route is to just commit stuff that we know executes, then file issues about it not being idiomatic, so we can go back and fix it. But this back-and-forward discussion with long response intervals and nothing produced is slowing us down for no good reason.

When you're at the stage we are with a product, churning even one user is very bad for progress, and because the product is immature there will be many small issues (such as a lack of code examples) that blocks users. If the blocking issue is not fixed promptly, the user will churn.

**Comment by uppfinnarn** [comment]
I would like to point out that I was out of the country for 7 of those days, and you also a) included a commit from a different PR (which is STILL THERE), and b) committed a massive blob of (at first) broken code.

In its current form, this  is not good example code, and I've told you why. It doesn't illustrate how to use k6, it illustrates how to shoot yourself in the foot and produce code that a) doesn't handle errors in any meaningful way, and b) doesn't display properly in the post-test summary or when run against our cloud service. Reading this will teach people to do something nonsensical and hacky, that while it technically generates load like it should, will do so in a completely useless way and produce difficult-to-analzyze results.

1. USE GROUPS.
1. Name your variables consistently (`form_build_id` vs `defaultheaders`).
1. The comment above the user data is incorrect.
1. Why does thinktime() even exist??
1. There is no reason for there to be global variables (only constants; which should be `const`).
1. Don't number your checks like that???
1. Checkout flow should do `check(…) || throw new Error("…")`, not log to the console and proceed regardless.

**Comment by micsjo** [comment]
7. Errors are hard, logs are soft.

Don't do ```throw new Error("blaha")``` in a performance test. It will abort the current iteration and spam you with error messages. You want to keep track of what is happening but aborting the current iteration will give the _wrong_ results when analyzing. Logging is _usually_ filtered at runtime so you can keep it in for validating your scripts and when running your tests you just discard any log levels you don't need. 

There are fringe cases where you do want to abort the current iteration but let's avoid edge cases for the time being.

For single execution functional tests - it's a different use case and you might want to abort your test with an error.

**Comment by uppfinnarn** [comment]
Hm, I'd have thought it'd be more useful to abort the iteration if there's no sensible way to proceed (can't checkout without loading the cart, etc), but I can see what you're saying.

**Comment by ragnarlonn** [comment]
Again: the example shows how to simulate a certain type of REAL user flow. We have nothing like that at the moment, which means it adds value regardless of whether it uses idiomatic code or not. Of course this script needs improvement, that is not the issue here. I'd rather have people successfully shoot themselves in the foot than wonder where the hell the gun could be, and decide to go to another dealer. 

In my mind, we need to prioritize documentation and script samples, and I don't see anyone else working on it. We can argue about details of this PR, but I think there are two basic issues: 1) our (in)ability to compromise on quality in the short term when people desperately need something and 2) a slow feedback loop that makes the problem worse.

But if everyone else thinks we're doing OK, that it is better to wait a couple of weeks with code examples so we get them exactly right, and that the current speed-vs-quality ambition level is right for this stage of the project - then I'll just keep my mouth shut under protest ;)

**Comment by uppfinnarn** [comment]
Apologies for sounding like something straight out of a Torvalds email, but bad code is bad code. Bad code most certainly isn't good sample code, time pressure or not.

What's slowing down the feedback loop isn't that I'm being pedantic, because I'm not right now, it's that you've spent more time arguing here than it'd have taken to fix the issues I've pointed out to you several times.

I'm at the office right now if you want me to help you in person. You can reach me on Slack. But I'm not going to merge this code in its current form.

**Comment by ragnarlonn** [comment]
If it is so fast to fix them, and you don't want us to waste time, why don't you just fix the issues and merge?  As you probably know, I am on paternity leave today and shouldn't be here arguing at all.

**Comment by uppfinnarn** [comment]
I'm up over my ears in other things, @robingustafsson, can you do it?

**Comment by robingustafsson** [comment]
Yay, great to see progress here 😄

**Comment by ragnarlonn** [comment]
Seems to work well, but crashes often (issue #144 I guess) when using http.batch() to fetch the static resources if I use more than 1 VU. Also, the output looks somewhat weird due to #143

**Comment by uppfinnarn** [comment]
There's some inconsistent indentation still, but other than that it's looking good!

**Comment by ragnarlonn** [comment]
Excellent!  Would you mind telling me where you see the inconsistent indentation?

**Comment by uppfinnarn** [comment]
I noticed a couple, but it'll be really obvious and/or fixed if you just convert the indentation to tabs.

**Comment by ragnarlonn** [comment]
Ah, unwanted space, I see. And I just found this great feature in VS Code - "Toggle render whitespace". Makes it easy to see what kind of whitespace you have.

**Pull request merged**
