### PR TITLE
preload grafana dashboard with docker-compose setup

### PR DESCRIPTION
**Pull request by jeevananthank**
Today's setup of docker-compose does not preload the dashboard when running the tests locally. This PR solves the issues and detailed description is in the link below.

The grafana dashboard used here is more generic and simple and one can update as per their needs. 

https://community.k6.io/t/preload-grafana-dashbaord-with-docker-compose-setup/874

### CODE REVIEW

**Review by MStoykov — APPROVED** [review]
LGTM!

I have some reservations about us putting, even more, grafana specific things in the k6 repo ... because even now people ask us questions that are grafana/influxdb related. And to be perfectly honest I don't think we should be the one trying to answer them, and usually, it requires that we go read the grafana/influxdb documentation to figure it out, which arguably should be what, the person who asked the question, have done in the first place.

**Review by simskij — APPROVED** [review]
Looks good to me!

**Review by na-- — APPROVED** [review]
I haven't actually tried the new default dashboard, but considering we're soon going to move the docker-compose files to a separate example repo (https://github.com/loadimpact/k6/issues/1614), LGTM :sweat_smile:

**Comment by simskij** [comment]
Thank you so much for your contribution, @jeevananthank! 🙏🏼

**Pull request merged**
