### PR TITLE
Report remote IP/port, closes #186

### LINKED ISSUE #186: return ip address
We'd like the ability to extract the ip address returned please?

### PR DESCRIPTION
**Pull request by ragnarlonn**

### CODE REVIEW

**Comment by liclac** [comment]
Please add this to the js2 runner as well

**Comment by liclac** [comment]
Ah, use [net.SplitHostPort](https://godoc.org/net#SplitHostPort) rather than strings.Split() or this will choke on IPv6 addresses.

**Comment by ragnarlonn** [comment]
Clever!  So should HTTPResponse.remotePort be an integer, or a string?  SplitHostPort returns a string for both Host and Port, but I think people will assume an integer for the port number, and I assume (?) we will never see port "http" here.

**Comment by liclac** [comment]
It's a string because `http://google.com:http/` is *technically valid*, it's just really silly and won't work with most HTTP libraries… just parsing it as a string and discarding the error is fine, an invalid port would just return 0 that way.

**Pull request merged**
