### PR TITLE
Add test case missing in borjacampina's batch req PR

### PR DESCRIPTION
**Pull request by robingustafsson**
Not sure how to do this in a better way, but this PR adds a test case for https://github.com/loadimpact/k6/pull/297.

### CODE REVIEW

**Comment by robingustafsson** [comment]
**Note**: that the test will fail until merged with https://github.com/loadimpact/k6/pull/297.

**Comment by liclac** [comment]
Please make this PR against @borjacampina's fork instead!

**Comment by robingustafsson** [comment]
@liclac Fine, I'll try that, but feels like an overly complicated process.

**Comment by liclac** [comment]
It may be, but it's the proper way to do it. If there's no response, I'll merge and verify manually.

**Pull request closed without merging**
