### PR TITLE
Added TLS handshake timing metrics.

### LINKED ISSUE #188: TCP and TLS handshake timings.
Can we add TLS handshake timings?

### PR DESCRIPTION
**Pull request by antekresic**
Added TLS handshake timing metrics. 

Closes #188

### CODE REVIEW

**Comment by liclac** [comment]
👍 

Just one thing: "handshaking" reads strange, and doesn't specify whether it's the TCP or TLS handshake. Maybe `http_req_tls_shaking` or something like that? `http_req_tls_neg` (as in "negotiating")?

**Comment by antekresic** [comment]
I agree, naming is a little off. I updated it to be more understandable.

Thanks for the feedback!

**Comment by liclac** [comment]
What the heck happened to the diff? I'm genuinely confused, a bunch of changes that are already in master somehow got in there, and I can't tell what actually changed anymore...

**Comment by antekresic** [comment]
Sorry about that, I merged changes from master to my feature fork, to avoid conflicts when merging the PR and this happened. If you want, I can make a new PR for this, to cleanup the diff.

**Comment by liclac** [comment]
Looks like you can fix it this way: https://stackoverflow.com/a/38016309

**Comment by robingustafsson** [comment]
@antekresic Have you had a change to look at fixing the diff? If it's less time consuming a new PR is fine.

**Comment by antekresic** [comment]
Sorry about the late reply, holidays and work stuff... I've tried rebasing the branch but I'm having no luck. I will create a new PR for this once this one is rejected, that should sort things out.

**Comment by robingustafsson** [comment]
No problem at all, we're thankful for your contribution. Ok great, I'll close this PR then.

**Pull request closed without merging**
