### PR TITLE
Intermediate README fix

### PR DESCRIPTION
**Pull request by ragnarlonn**
We need to update logo, animation, probably "Development setup" and think about overall structure of the README, but this PR at least includes prominent links to k6.io and docs.k6.io, plus includes some basic "getting started" info.

### CODE REVIEW

**Comment by liclac** [comment]
We kind of need that introduction in there, a step by step guide on how to do something doesn't fill the same purpose as explaining what the program does and how it differs from similar tools.

**Comment by ragnarlonn** [comment]
My thought was to have most real content on he docs site instead (as much as possible) and just link to it. Otherwise we have two places to update when we change things. This particular text is already on the docs.k6.io site, if you look at https://docs.k6.io/docs/running-k6. I also prefer to introduce something by example rather than theory. If you still think it has to be in the README, perhaps we can put it at the end?

**Comment by liclac** [comment]
We could totally do with a shorter introduction if you prefer, but it needs to be there. If people stumble in here, they should understand from reading the README what the program is and what it does, and why they should care enough to open an external site.

**Comment by ragnarlonn** [comment]
I think they get what the program is and does just from the first paragraph, but ok I'll put it back after the links?

**Comment by liclac** [comment]
Sure, I do agree that we should probably shorten down the intro and move parts into the docs, but this works for now.

**Pull request merged**
