### PR TITLE
Add test coverage

### PR DESCRIPTION
**Pull request by borjacampina**
WIP

### CODE REVIEW

**Comment by liclac** [comment]
Still giving me the same results, even with an updated $COVERALLS_TOKEN from the project page…

**Comment by borjacampina** [comment]
After a few days of testing (playing with their API directly too).. I think coveralls must have some issues with their circleci integration. Now, I use codecov and.. it works!: https://codecov.io/gh/loadimpact/k6/branch/feature%2Ftest-coverage

**Comment by liclac** [comment]
What's with that new empty file?

Also: is this good to merge?

**Comment by borjacampina** [comment]
This is cool for circleci

**Pull request merged**
