### PR TITLE
fixed issue with obj form request in batch mode

### LINKED ISSUE #295: http.batch invalid method error
Running the script:
```js
import { group } from 'k6';
import http from 'k6/http';

export default function() {

  group("page_1", function() {
    http.batch([{
      url: "https://loadimpact.com/",
      method: "GET"
    }]);
  });
}
```
I get error:
```
ERRO[0032] GoError: net/http: invalid method "HTTPS://LOADIMPACT.COM/"
```

I wonder if arguments can be mixed up, and yes, after swapping the properties like:
```
    http.batch([{
      method: "GET",
      url: "https://loadimpact.com/"
    }]);
```
it works good.

### PR DESCRIPTION
**Pull request by borjacampina**
closes #295 

Maybe this is not the perfect solution. I hope it helps to solve it as reference. 

In batch mode (shorthand and object form requests), k6 obtains the method and url parameters given their position (0=method, 1=url) only, so when we use object form requests only uses their position and the object keys (url and method) are ignored. That means, for a request object like "{url:"http://domain.com", method:"get"}", http://domain.com is misinterpreted as method parameter.  

For shorthand requests, obj is a []interface{} type, their obj.Keys() are "0", "1"... 
For object form requests, obj is a map[string]interface{} type, their obj.Keys() are "url", "method"...  

This PR allows us to use "0" as an alias for "method" and "1" for "url" in object form requests: "{0:"http://domain.com", 1:"get"}". We can avoid this issue: if the obj object is a map type (v.ExportType().Kind().String() == "map" ??) we only should handle "method" and "url" keys. I can include it if it's important.

### CODE REVIEW

**Comment by liclac** [comment]
Huh, this seems to have been put in the docs without actually being part of the spec… but hey, it looks handy. Just add some unit tests too!

**Comment by borjacampina** [comment]
Sorry for the delay. I have merged @robingustafsson's test case

**Comment by robingustafsson** [comment]
Great, thanks @borjacampina! Ping @liclac.

**Comment by liclac** [comment]
:+1:

**Pull request merged**
