### PR TITLE
Quick fix for PR #235

### PR DESCRIPTION
**Pull request by gbts**
I missed the !go1.8 tag in the 1.7 file in the last PR, this should build OK now.

### CODE REVIEW

**Comment by liclac** [comment]
Question: what will happen when Go 1.10 comes out? If this is how the build tags work, maybe it's a better idea to have a base map and then have per-version files that *add* to that map instead?

**Comment by gbts** [comment]
But what if a newer version removes support for one of the old ciphers? Personally I would also prefer it if each file was a 1-1 representation of the cipher list in the docs. If more ciphers are added or removed then one can easily copy the new list verbatim instead of the more error-prone way of comparing the docs from each version to find out when each cipher was added.

But obviously since you're the long term maintainer it's up to you, so if you prefer it that way let me know and I'll change it.

One other thing, I'm going to remove the 1.9 tag from the 1.8 file. It's redundant since 1.9 will also have the 1.8 defined and having the 1.9 tag inside the 1.8 file is just confusing (build tags are confusing me enough as they are!).

**Comment by gbts** [comment]
Done!

**Comment by robingustafsson** [comment]
@gbts Sorry to contact you like this, but I can't find another way to reach you as I don't have an email adress or other contact information.

We've introduced a Contributor License Agreement for k6, and are reaching out to all contributors to ask them for their signature.

You can review and sign the CLA here: https://cla-assistant.io/loadimpact/k6

Hope this message reaches you and that there won't be any hinderances to get the CLA signed 😃

You can reach me at robin@loadimpact.com or via k6 Slack (I'm "robin" in there) if you have any questions. Thank you!

**Pull request merged**
